In [1]:
import numpy as np

In [25]:
a = np.array([1.0, np.NAN, 0])
b = np.array([1.0, 1.0, 3.0])

In [26]:
np.intersect1d(a, b)

array([1.])

In [27]:
np.union1d(a, b)

array([ 0.,  1.,  3., nan])

In [28]:
np.setdiff1d(a, b)

array([ 0., nan])

In [29]:
np.setxor1d(a, b)

array([ 0.,  3., nan])