In [1]:
import numpy as np

In [3]:
a = np.arange(-1, 1, 0.1)
a

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [6]:
np.abs(a) == np.fabs(a)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [8]:
np.modf(a)

(array([-0.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
        -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
        -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
         2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
         6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01]),
 array([-1., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]))

In [9]:
np.isinf(a)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [10]:
np.isfinite(a)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [11]:
a[10] = np.nan

In [13]:
np.fabs(a)

array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, nan, 0.1, 0.2,
       0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [14]:
a = np.arange(-1, 1, 0.1)
b = np.arange(1, -1, -0.1)

In [15]:
np.maximum(a, b)

array([1.00000000e+00, 9.00000000e-01, 8.00000000e-01, 7.00000000e-01,
       6.00000000e-01, 5.00000000e-01, 4.00000000e-01, 3.00000000e-01,
       2.00000000e-01, 1.00000000e-01, 2.22044605e-16, 1.00000000e-01,
       2.00000000e-01, 3.00000000e-01, 4.00000000e-01, 5.00000000e-01,
       6.00000000e-01, 7.00000000e-01, 8.00000000e-01, 9.00000000e-01])

In [16]:
np.minimum(a, b)

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16, -1.00000000e-01,
       -2.00000000e-01, -3.00000000e-01, -4.00000000e-01, -5.00000000e-01,
       -6.00000000e-01, -7.00000000e-01, -8.00000000e-01, -9.00000000e-01])

In [17]:
np.copysign(a, b)

array([ 1.00000000e+00,  9.00000000e-01,  8.00000000e-01,  7.00000000e-01,
        6.00000000e-01,  5.00000000e-01,  4.00000000e-01,  3.00000000e-01,
        2.00000000e-01,  1.00000000e-01,  2.22044605e-16, -1.00000000e-01,
       -2.00000000e-01, -3.00000000e-01, -4.00000000e-01, -5.00000000e-01,
       -6.00000000e-01, -7.00000000e-01, -8.00000000e-01, -9.00000000e-01])

In [18]:
a[10] = np.nan
b[0] = np.nan

In [19]:
np.maximum(a, b)

array([nan, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, nan, 0.1, 0.2,
       0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [20]:
np.fmax(a, b)

array([-1.00000000e+00,  9.00000000e-01,  8.00000000e-01,  7.00000000e-01,
        6.00000000e-01,  5.00000000e-01,  4.00000000e-01,  3.00000000e-01,
        2.00000000e-01,  1.00000000e-01,  2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])