In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.arange(0, 16, 1.0).reshape((4, 4))
a[:, 0] = np.nan
a[0, 1] = np.nan

In [3]:
a

array([[nan, nan,  2.,  3.],
       [nan,  5.,  6.,  7.],
       [nan,  9., 10., 11.],
       [nan, 13., 14., 15.]])

In [5]:
df = pd.DataFrame(a)
df

0     1     2     3
0 NaN   NaN   2.0   3.0
1 NaN   5.0   6.0   7.0
2 NaN   9.0  10.0  11.0
3 NaN  13.0  14.0  15.0

In [6]:
df.fillna(0)

0     1     2     3
0  0.0   0.0   2.0   3.0
1  0.0   5.0   6.0   7.0
2  0.0   9.0  10.0  11.0
3  0.0  13.0  14.0  15.0

In [10]:
df.drop(labels=[0, 1], axis=1)

2     3
0   2.0   3.0
1   6.0   7.0
2  10.0  11.0
3  14.0  15.0

In [11]:
a = np.random.binomial(3, 0.5, (100, 3))
a

array([[0, 1, 2],
       [1, 1, 2],
       [0, 1, 3],
       [2, 0, 3],
       [3, 1, 3],
       [3, 3, 0],
       [3, 2, 0],
       [2, 2, 1],
       [2, 1, 2],
       [1, 3, 1],
       [1, 1, 2],
       [1, 2, 2],
       [2, 2, 2],
       [2, 2, 1],
       [1, 0, 0],
       [1, 2, 2],
       [1, 3, 2],
       [1, 2, 2],
       [3, 0, 3],
       [0, 0, 2],
       [1, 2, 2],
       [3, 2, 2],
       [2, 1, 2],
       [0, 2, 1],
       [1, 1, 2],
       [1, 3, 1],
       [0, 1, 1],
       [2, 2, 3],
       [3, 1, 1],
       [1, 1, 3],
       [2, 3, 1],
       [1, 2, 2],
       [1, 3, 1],
       [1, 1, 0],
       [2, 2, 1],
       [1, 0, 1],
       [2, 1, 1],
       [3, 1, 2],
       [1, 1, 2],
       [0, 2, 1],
       [0, 1, 1],
       [0, 3, 1],
       [0, 2, 1],
       [3, 2, 2],
       [3, 2, 1],
       [2, 0, 2],
       [2, 1, 2],
       [1, 2, 2],
       [2, 1, 2],
       [1, 1, 0],
       [1, 1, 2],
       [0, 3, 2],
       [2, 1, 2],
       [1, 0, 0],
       [3, 2, 1],
       [1,

In [13]:
df = pd.DataFrame(a)
group_df = df.groupby([0])

In [26]:
for group_id, value in group_df:
    print(group_id, value)

0     0  1  2
0   0  1  2
2   0  1  3
19  0  0  2
23  0  2  1
26  0  1  1
39  0  2  1
40  0  1  1
41  0  3  1
42  0  2  1
51  0  3  2
64  0  3  2
71  0  0  3
74  0  2  1
90  0  0  1
95  0  0  0
98  0  2  1
1     0  1  2
1   1  1  2
9   1  3  1
10  1  1  2
11  1  2  2
14  1  0  0
15  1  2  2
16  1  3  2
17  1  2  2
20  1  2  2
24  1  1  2
25  1  3  1
29  1  1  3
31  1  2  2
32  1  3  1
33  1  1  0
35  1  0  1
38  1  1  2
47  1  2  2
49  1  1  0
50  1  1  2
53  1  0  0
55  1  1  1
57  1  3  2
58  1  1  1
59  1  2  3
61  1  1  2
63  1  1  1
66  1  1  2
68  1  1  1
73  1  0  1
75  1  0  2
76  1  1  1
78  1  2  3
79  1  2  2
80  1  1  3
84  1  2  2
85  1  1  2
86  1  1  0
87  1  0  2
93  1  0  1
97  1  3  1
99  1  2  1
2     0  1  2
3   2  0  3
7   2  2  1
8   2  1  2
12  2  2  2
13  2  2  1
22  2  1  2
27  2  2  3
30  2  3  1
34  2  2  1
36  2  1  1
45  2  0  2
46  2  1  2
48  2  1  2
52  2  1  2
56  2  2  2
60  2  3  1
62  2  3  1
65  2  1  3
67  2  1  0
69  2  3  2
72  2  1  2
77  2  2  

In [35]:
def apply_func(ele):
    print(ele.info())
group_df.agg(apply_func)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16 entries, 0 to 98
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       16 non-null     int64
 1   1       16 non-null     int64
 2   2       16 non-null     int64
dtypes: int64(3)
memory usage: 512.0 bytes
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 42 entries, 1 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       42 non-null     int64
 1   1       42 non-null     int64
 2   2       42 non-null     int64
dtypes: int64(3)
memory usage: 1.3 KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28 entries, 3 to 96
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       28 non-null     int64
 1   1       28 non-null     int64
 2   2       28 non-null     int64
dtypes: int64(3)
memory usage: 896.0 bytes
None
<class 'pandas.core.frame.Data

1   2
0        
0 NaN NaN
1 NaN NaN
2 NaN NaN
3 NaN NaN

In [22]:
np.setxor1d(np.array([1, 2, 3]), np.array([4, 5, 6]))

array([1, 2, 3, 4, 5, 6])

In [23]:
for index, row in df.iterrows():
    print(index, row)

0 0    0
1    1
2    2
Name: 0, dtype: int64
1 0    1
1    1
2    2
Name: 1, dtype: int64
2 0    0
1    1
2    3
Name: 2, dtype: int64
3 0    2
1    0
2    3
Name: 3, dtype: int64
4 0    3
1    1
2    3
Name: 4, dtype: int64
5 0    3
1    3
2    0
Name: 5, dtype: int64
6 0    3
1    2
2    0
Name: 6, dtype: int64
7 0    2
1    2
2    1
Name: 7, dtype: int64
8 0    2
1    1
2    2
Name: 8, dtype: int64
9 0    1
1    3
2    1
Name: 9, dtype: int64
10 0    1
1    1
2    2
Name: 10, dtype: int64
11 0    1
1    2
2    2
Name: 11, dtype: int64
12 0    2
1    2
2    2
Name: 12, dtype: int64
13 0    2
1    2
2    1
Name: 13, dtype: int64
14 0    1
1    0
2    0
Name: 14, dtype: int64
15 0    1
1    2
2    2
Name: 15, dtype: int64
16 0    1
1    3
2    2
Name: 16, dtype: int64
17 0    1
1    2
2    2
Name: 17, dtype: int64
18 0    3
1    0
2    3
Name: 18, dtype: int64
19 0    0
1    0
2    2
Name: 19, dtype: int64
20 0    1
1    2
2    2
Name: 20, dtype: int64
21 0    3
1    2
2    2
Name: 21,

In [36]:
df

0  1  2
0   0  1  2
1   1  1  2
2   0  1  3
3   2  0  3
4   3  1  3
.. .. .. ..
95  0  0  0
96  2  0  1
97  1  3  1
98  0  2  1
99  1  2  1

[100 rows x 3 columns]

In [39]:
def func2(ele):
    print(ele)
df.apply(func2)

0     0
1     1
2     0
3     2
4     3
     ..
95    0
96    2
97    1
98    0
99    1
Name: 0, Length: 100, dtype: int64
0     1
1     1
2     1
3     0
4     1
     ..
95    0
96    0
97    3
98    2
99    2
Name: 1, Length: 100, dtype: int64
0     2
1     2
2     3
3     3
4     3
     ..
95    0
96    1
97    1
98    1
99    1
Name: 2, Length: 100, dtype: int64


0    None
1    None
2    None
dtype: object

In [42]:
df.columns = ['a', 'b', 'c']

In [45]:
df.a.head()

0    0
1    1
2    0
3    2
4    3
Name: a, dtype: int64

In [48]:
df.columns = range(3)

In [51]:
df[0].name

0

In [52]:
series = pd.Series([1, 2, 3])
series.name

In [53]:
df

0  1  2
0   0  1  2
1   1  1  2
2   0  1  3
3   2  0  3
4   3  1  3
.. .. .. ..
95  0  0  0
96  2  0  1
97  1  3  1
98  0  2  1
99  1  2  1

[100 rows x 3 columns]

In [56]:
del df[0]

In [62]:
temp_S = df[1].copy()

In [63]:
temp_S

0     2
1     1
2     1
3     0
4     1
     ..
95    0
96    0
97    3
98    2
99    2
Name: 1, Length: 100, dtype: int64

In [64]:
temp_S[0] = 1
temp_S

0     1
1     1
2     1
3     0
4     1
     ..
95    0
96    0
97    3
98    2
99    2
Name: 1, Length: 100, dtype: int64

In [65]:
df

1  2
0   2  2
1   1  2
2   1  3
3   0  3
4   1  3
.. .. ..
95  0  0
96  0  1
97  3  1
98  2  1
99  2  1

[100 rows x 2 columns]

In [69]:
df1 = pd.DataFrame(np.arange(1, 10, 1).reshape((3, 3)), index=[1, 2, 3])

In [70]:
df1

0  1  2
1  1  2  3
2  4  5  6
3  7  8  9

In [71]:
df2 = pd.DataFrame(df1.iloc[:, :2])

In [72]:
df2

0  1
1  1  2
2  4  5
3  7  8