In [2]:
import numpy as np
# import datetime
# import numpy as np
# import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
# import statsmodels as sm
# import requests
# import re
import json

In [1]:
def load_json(file_name):
    with open(file_name, "r") as f:
        data = json.load(f)
    return data

In [14]:
old = load_json("./old.json")
new = load_json("./new.json")

In [15]:
old = np.asarray(list(old.values()))
new = np.asarray(list(new.values()))

In [18]:
old[: 100] == new[:100]

array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False,  True,  True, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [19]:
old[:9]

array([80, 75,  3,  4, 20,  0,  0,  0,  8])

In [20]:
new[:9]

array([80, 75,  3,  4, 10,  0,  0,  0,  0])

In [1]:
import matplotlib.pyplot as plt

In [2]:
import numpy as np

In [3]:
plt.figure(figsize=(100, 100), dpi=100)

<Figure size 10000x10000 with 0 Axes>

<Figure size 10000x10000 with 0 Axes>

In [4]:
plt.rcParams['font.sans-serif'] = ['SimHei']

In [5]:
plt.rcParams['axes.unicode_minus'] = False

In [1]:
import chardet

In [6]:
chardet.detect("¼ì²âÎı¾±àÂë¸ñʽ".encode())

{'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}

In [29]:
"¼ì²âÎı¾±àÂë¸ñʽ".encode("ISO-8859-1")

b'\xbc\xec\xb2\xe2\xce\xc4\xb1\xbe\xb1\xe0\xc2\xeb\xb8\xf1\xca\xbd'

In [ ]:
C ViewerµÄÅäÖÃÎļþ£¬½â¾övnc