In [1]:
import numpy as np
# import datetime
# import numpy as np
# import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
# import statsmodels as sm
# import requests
# import re
import json

In [3]:
def load_json(file_name):
    with open(file_name, "r") as f:
        data = json.load(f)
    return data

In [4]:
old = load_json("./old.json")
new = load_json("./new.json")

In [15]:
old = np.asarray(list(old.values()))
new = np.asarray(list(new.values()))

In [18]:
old[: 100] == new[:100]

array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False,  True,  True, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [19]:
old[:9]

array([80, 75,  3,  4, 20,  0,  0,  0,  8])

In [20]:
new[:9]

array([80, 75,  3,  4, 10,  0,  0,  0,  0])

In [1]:
import matplotlib.pyplot as plt

In [2]:
import numpy as np

In [3]:
plt.figure(figsize=(100, 100), dpi=100)

<Figure size 10000x10000 with 0 Axes>

<Figure size 10000x10000 with 0 Axes>

In [4]:
plt.rcParams['font.sans-serif'] = ['SimHei']

In [5]:
plt.rcParams['axes.unicode_minus'] = False

In [67]:
import chardet

In [69]:
chardet.detect("¼ì²âÎı¾±àÂë¸ñʽ")

{'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}

In [96]:
def encode_text(text, encoding="utf-8"):
    data = text.encode(encoding)
    print("原始结构:", data)
    print("长度:", len(data))
    print("整数列表:", [e for e in data])
    bin_list = ["{:08b}".format(e) for e in data]
    print("二进制字符串列表:", bin_list)
    bin_all = "".join(bin_list)
    print("0出现次数:{}, 1出现次数:{}".format(bin_all.count("0"), bin_all.count("1")))

def transfrom_from_vnc(text, from_encoding="GB2312"):
    return text.encode("latin1").decode(from_encoding)

In [77]:
encode_text("ÖÆ", "utf-8")
encode_text("»»", "utf-8")
encode_text("ÔÚ", "utf-8")

长度: 4
整数列表: [195, 150, 195, 134]
二进制字符串列表: ['11000011', '10010110', '11000011', '10000110']
0出现次数:17, 1出现次数:15
长度: 4
整数列表: [194, 187, 194, 187]
二进制字符串列表: ['11000010', '10111011', '11000010', '10111011']
0出现次数:14, 1出现次数:18
长度: 4
整数列表: [195, 148, 195, 154]
二进制字符串列表: ['11000011', '10010100', '11000011', '10011010']
0出现次数:17, 1出现次数:15


In [97]:
transfrom_from_vnc("ÖÆ")

'制'

In [87]:
# encode_text("制", encoding="utf-8")
# encode_text("制", encoding="utf-16")
encode_text("制", encoding="GB2312")
encode_text("换", encoding="GB2312")
encode_text("在", encoding="GB2312")

原始结构: b'\xd6\xc6'
长度: 2
整数列表: [214, 198]
二进制字符串列表: ['11010110', '11000110']
0出现次数:7, 1出现次数:9
原始结构: b'\xbb\xbb'
长度: 2
整数列表: [187, 187]
二进制字符串列表: ['10111011', '10111011']
0出现次数:4, 1出现次数:12
原始结构: b'\xd4\xda'
长度: 2
整数列表: [212, 218]
二进制字符串列表: ['11010100', '11011010']
0出现次数:7, 1出现次数:9


In [95]:
bad = "ÔÚPythonÖУ¬½«Ò»¸ö±íʾʮÁù½øÖÆ×Ö·û´®µÄUnicode×Ö·û´®£¨Èç'\xd6\xc6'£©×ª»»Îª×Ö½Ú×Ö·û´®£¨bytes£©¿ÉÒÔʹÓÃÒÔÏ·½·¨£º".encode("latin1").decode("GB2312")
bad

"在Python中，将一个表示十六进制字符串的Unicode字符串（如'制'）转换为字节字符串（bytes）可以使用以下方法："

In [43]:
good = "换".encode("utf-8")
[x for x in good], len(good)

([230, 141, 162], 3)

In [26]:
"»»".encode("utf-16")

b'\xff\xfe\xbb\x00\xbb\x00'